id: I452ADABB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:53:55+00:00'
last_modified: '2022-06-10T09:14:42.301219+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9751
  title: ཞྭ་ལུའི་ཆོས་སྤྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F0CD:
      image_group_id: I1KG9764
      title: Volume 1 of zhwa lu'i chos spyod/
      total_pages: 426
      order: 1
      base_file: F0CD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
